[workspace]
resolver = "1"
members = [
  "uvm_core",
  "uvm_cli",
  "uvm_install_graph",
  "uvm_live_platform",
  "uvm_move_dir",
  "commands/*",
  "install/*"
, "unity-version", "unity-hub", "unity-types"]
