[package]
name = "uvm-clear"
version = "2.3.0"
authors = ["Manfred Endres <manfred.endres@tslarusso.de>"]
edition = "2018"
[dependencies]
console = "0.6.1"
serde = "1.0"
serde_derive = "1.0"
error-chain = "0.12.0"
uvm_cli = { path = "../../uvm_cli" }
uvm_core = { path = "../../uvm_core" }
