[package]
name = "uvm-uninstall"
version = "2.0.0"
authors = ["Manfred Endres <manfred.endres@tslarusso.de>"]

[dependencies]
console = "0.6.1"
serde = "1.0"
serde_derive = "1.0"
uvm_cli = { path = "../../uvm_cli" }
uvm_core = { path = "../../uvm_core" }
uvm_install_core = { path = "../uvm_install_core" }
