[package]
name = "uvm-versions"
version = "2.3.0"
authors = ["Manfred Endres <manfred.endres@tslarusso.de>"]
edition = "2018"
[dependencies]
console = "0.9.1"
regex = "0.2"
itertools = "0.8.1"
serde = "1.0"
log = "0.4.5"
serde_derive = "1.0"
indicatif = "0.15.0"
uvm_cli = { path = "../../uvm_cli" }
uvm_core = { path = "../../uvm_core" }
