[package]
name = "uvm-versions"
version = "2.3.0"
authors = ["Manfred Endres <manfred.endres@tslarusso.de>"]
edition = "2018"
description = "List available Unity versions to install."
[dependencies]
anyhow = "1.0.55"
console = "0.9.1"
regex = "1.4"
itertools = "0.9.0"
serde = "1.0"
structopt = "0.3"
log = "0.4.11"
serde_derive = "1.0"
indicatif = "0.15.0"
uvm_cli = { path = "../../uvm_cli" }
uvm_core = { path = "../../uvm_core" }
