[package]
name = "uvm-versions"
version = "2.0.1"
authors = ["Manfred Endres <manfred.endres@tslarusso.de>"]

[dependencies]
console = "0.6.1"
regex = "0.2"
itertools = "0.7.8"
serde = "1.0"
serde_derive = "1.0"
indicatif = "0.9.0"
uvm_cli = { path = "../../uvm_cli" }
uvm_core = { path = "../../uvm_core" }
uvm_install_core = { path = "../uvm_install_core" }
