[package]
name = "uvm"
version = "2.3.0"
authors = ["Manfred Endres <manfred.endres@tslarusso.de>"]
edition = "2018"
description = "cli utility to install and manage unity versions"

[dependencies]
anyhow = "1.0.50"
console = "0.9.1"
uvm_cli = { path = "../../uvm_cli" }
structopt = "0.3"