[package]
name = "uvm_cli"
version = "2.0.1"
authors = ["Manfred Endres <manfred.endres@tslarusso.de>"]

[dependencies]
flexi_logger = "0.9.2"
log = "0.4.5"
docopt = "1.0"
serde = "1.0"
serde_derive = "1.0"
uvm_core = { path = "../uvm_core" }
console = "0.6.1"
